scraper:
  base_url: "https://ottawa.ca/en/parking-roads-and-travel/parking"
  max_pages: 100
  max_depth: 6
  request_delay: 0.9
  max_workers: 6
  timeout: 15
  verify_ssl: false
  politeness: 1.0
  user_agent: "OttawaServicesAIChatbot/1.0 (+https://github.com/schmitech)"
  max_retries: 2
  jitter: 0.5

content:
  tokenizer: "cl100k_base"
  max_tokens_per_chunk: 1000
  min_chunk_size: 100
  excluded_patterns:
    - "/city-jobs/"
    - "/form/"
    - "/pay-or-purchase"
    - "/compliments"
    - "/track-your-service-request"
    - "/client-satisfaction-survey"
    - ".pdf"
    - ".jpg"
    - ".png"
    - ".gif"
    - ".jpeg"
    - ".doc"
    - ".docx"
    - "calendar"
    - "search"
    - "login"
    - "signin"
    - "signup"
    - "/fr-ca/"
    - "mailto:"
    - "tel:"
    - "javascript:"
    - "print="
    - "register.ottawa.ca"

model:
  base_model: "gemma2:9b"
  instruction_file: "model-files/gemma9b.txt"
  parameters:
    temperature: 0.3
    top_k: 50
    top_p: 0.9
    repeat_penalty: 1.1
    num_ctx: 4096
    num_thread: 8
  template: |
    {{ if .System }}<|start_header_id|>system<|end_header_id|>
    {{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>
    {{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>
    {{ .Response }}<|eot_id|>

output:
  directory: "ottawa_data"
  files:
    content: "content.json"
    metadata: "metadata.csv"
    training: "training_data.json"
    modelfile: "Modelfile" 